name: Avito Background Checker

on:
  schedule:
    - cron: '*/5 * * * *'  # Проверка каждые 5 минут
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run parser
        run: python scripts/parser.py